### ISSUE TITLE
Désactivation (Suppression) Récursive

### ISSUE THREAD

**Issue by RemyTombez** [OrifInformatique/plafor#10]
Faire en sorte que lors de la suppression d'une entrée d'une table dans la base de données, tout les entrées dans les tables liées qui contiennent une clé étrangère qui référence l'entrée qui va être supprimée seront aussi supprimées.

Un exemple concret est si l'utilisateur supprime un plan de formation (table _course_plan_) :

1. Cela supprimera aussi les domaines de compétences (table _competence_domain_) qui y sont liés.

2. Puis cela supprimera les compétences opérationnelles (table _operational_competence_) liées aux domaines de compétences qui seront supprimés.

3. Enfin seront supprimées les objectifs (table _objective_) liés aux compétences opérationnelles qui seront aussi supprimées.

**Comment by DidierViret** [comment]
Ne pas faire de suppression récursive, c'est trop dangereux, mais permettre de faire un "soft delete" sur un plan de formation, même si des domaines de compétence lui sont liés.
Soft delete signifie de mettre à "true" un booleen "archive", c'est une fonction fournie par MY_model.
