### ISSUE TITLE
Certaines fonctions delete_x du controleur Admin ne marche pas comme dans leur documentation

### ISSUE THREAD

**Issue by MestourBS** [OrifInformatique/plafor#30]
La plupart des fonctions delete_x du contrôleur mentionnent dans leur documentation que si $action est 2, l'objet est supprimé définitivement, mais cette fonctionnalité n'est pas programmée. Il faudrait ou bien enlever cette mention, ou bien programmer la fonctionnalité.

**Comment by DidierViret** [comment]
Il faut implémenter la possibilité de choisir entre une désactivation (soft delete) ou une suppression (hard delete) pour ces types d'objets :
- Plan de formation
- Domaine de compétence
- Compétence opérationnelle
- Objectif

Au niveau de l'interface, utiliser les mêmes couleurs de bouton et le même type de message que pour la suppression d'un utilisateur. Donner aussi la possibilité d'inclure les éléments archivés dans la liste et de les réactiver, toujours en suivant la même manière de faire que pour les utilisateurs.
