### ISSUE TITLE
Faire le point sur l'état de développement de l'application

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/plafor#51]
1. Installer l'application sur votre poste de travail
2. Générer la base de données et son contenu
3. Passer en revue les fonctionnalités disponibles
4. Faire un résumé des fonctionnalités disponibles et restant à développer, en commentaire de cette issue

**Comment by maximeor** [comment]
Fonctionnalités disponibles:

         fonctonnalités identiques à celle du packbase_v4
	-Connexion / Déconnexion
	-administration user
	-modification mot de passe

fonctionnalités supplémentaires présentes:
	-Liste des apprentis
	-Affichage des informations concernant les apprentis (Nom, date de création, formateur lié et formation suivies)
	-Affichage des informations concernant les plans de formation(num, nom du plan, date de création, domaines de compétences liés)
	-Affichage des domaines de compétences et leurs infos
	-Affichage des domaines de compétences et leur structure(A1, B2, C3), leur taxonomies et leurs détails(comp méthod, sociale, personnelle)
	-Affichage des objectifs, leur details et le nom de leur plan de formation. désactivation des objectifs
	-Ajout de plan de formation, ajout de domaines de compétence au plan de formation ajout de détail, modification de plan de formation OK, suppresion ok quand pas de domaine de compétence
	-Affichage des comp opéraitonnelles, ajout, modification, détails, désactivation OK

fonctionalités à compléter:	

-Bouton annuler à implémenter
-Affichage des informations concernant les formateurs
-Modification des formateurs, ne fonctionne pas corrèctement, le modifier pour ne pas ajouter un formateur supplémentaire, mais supprimer l'ancien et le remplacer
-Ajouter des formateurs, ne fonctionne pas corrèctement, ne pas laisser ajouter le même formateur
-Supprimer des formateurs, ne fonctionne pas, l'ajouter
-supprimer des plans de formation quand elle contient des domaines de compétence
-désactiver domaine de compétence pas ok quand nouveau
-modification du status de formation

**Comment by DidierViret** [comment]
TESTS FAITS DANS LA BRANCHE "master" ET PAS DANS LA "release 0.2"

Ce qui fonctionne :

- Liste des apprentis
- Détail d'un apprenti
- Liste des plans de formation
- Détail d'un plan de formation
- Modification d'un plan de formation
- Détail d'un domaine de compétences
- Modification d'un domaine de compétences
- Détail d'une compétence opérationnelle
- Détail d'un objectif
- La liste d'acquisition des objectifs d'un apprenti pour un plan de formation donné
- Ajout d'une formation liée à un apprenti

Fonctions manquantes ou bugs constatés :

- Possibilité d'ajouter plusieurs fois le même formateur à un apprenti.
- Manque un filtre pour afficher la liste des domaines de compétences uniquement d'un plan de formation choisi.
- Manque des filtres pour afficher la liste des compétences opérationnelles uniquement d'un domaine de compétences choisi.
- A l'ajout d'une compétence opérationnelle, il faut d'abord pouvoir sélectionner un plan de formation puis choisir le domaine de compétence.
- Manque des filtres pour afficher les objectifs d'un plan de formation choisi, ou d'un domaine de compétence, ou d'une compétence opérationnelle choisie.
- Les fonctions d'affichage des plans de formation, compétences opérationnelles ou objectifs sont dans le contrôleur "apprentice"
- Manque la possibilité de modifier le statut d'acquisition d'un objectif
- L'ajout de commentaire dans un statut d'acquisition ne fonctionne pas
