### ISSUE TITLE
Recreate Models

### ISSUE THREAD

**Issue by maximeor** [OrifInformatique/plafor#53]

**Comment by DidierViret** [comment]
- J'ai remarqué par hasard que le modèle "acquisitionLevelModel" est lié par erreur à la table "comment".
- Je n'ai pas compris l'implémentation des fonctions "get", par exemple acquisitionStatusModel, fonction getObjective, ligne 28, pourquoi la valeur fk_objective est notée sous forme de texte ?
- Il faudra également prévoir des fonctions get dans l'autre sens, par exemple pour récupérer tous les domaines de compétence d'un plan de formation donné.

**Comment by maximeor** [comment]
Ces models contiennent des erreur, les relations ne sont pas dans le bon sens.

**Comment by maximeor** [comment]
Je vais les refaire
