### ISSUE TITLE
Transférer l'administration des plans de formation vers CI 4

### ISSUE THREAD

**Issue by DidierViret** [OrifInformatique/plafor#58]
Créer un nouveau contrôleur plafor/Controllers/Admin.php

Transférer dans ce contrôleur les méthodes qui permettent de gérer les plans de formation. La gestion de tout le contenu d'un plan de formation se fera depuis l'onglet "Plans de formation", y compris l'ajout de domaines de compétences, de compétences opérationnelles ou d'objectifs.

**Comment by maximeor** [comment]
gestion des apprentis:
Formateur: possibilité de lister les apprentis, mais seulement de les attribuer à lui même
